tor-memquota: Downgrade to 0.18
I was unable to publish tor-memquota 0.19 because I don't have ownership
```
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error (status 403 Forbidden): this crate exists but you don't seem to be an owner. If you believe this is a mistake, perh
aps you need to accept an invitation to be an owner before publishing.
```

Let's downgrade it for now.