maint/downgrade-dependencies: Update exceptions.
Fixes the `minimal-versions` failure:

```
error: package ID specification `futures-lite@1.0.0` did not match any packages
Did you mean one of these?
  futures-lite@2.0.0
```

(we don't actually need to un-downgrade `futures-lite` anymore)

But we *do* need to un-downgrade `event-listener`
(`async-global-executor` needs `event_listener::EventListener` to be `UnwindSafe`,
and in `event-listener 3.0.0`, they are not)